apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app.dev-ns-02.dieunkrauts.de.20231215151506.0.0
spec:
  refName: tanzu-java-web-app.dev-ns-02.dieunkrauts.de
  version: 20231215151506.0.0
  releaseNotes: |
    Release v20231215151506.0.0 of package tanzu-java-web-app.dev-ns-02.dieunkrauts.de
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.dieunkrauts.de/tap/workloads/tanzu-java-web-app-dev-ns-02-bundle@sha256:aea4cc87b893d784808b5e0fc0fa3a5f871038281e51ac02028d05e7c1785030
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

