apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app.dev-ns-02.dieunkrauts.de.20231205181830.0.0
spec:
  refName: tanzu-java-web-app.dev-ns-02.dieunkrauts.de
  version: 20231205181830.0.0
  releaseNotes: |
    Release v20231205181830.0.0 of package tanzu-java-web-app.dev-ns-02.dieunkrauts.de
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.dieunkrauts.de/tap/workloads/tanzu-java-web-app-dev-ns-02-bundle@sha256:6c8a011083765f3bbd359e3203fd09700346083e9d5884a152f76a3cbb8c6e8d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

