apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app.dev-ns-02.dieunkrauts.de.20231207170000.0.0
spec:
  refName: tanzu-java-web-app.dev-ns-02.dieunkrauts.de
  version: 20231207170000.0.0
  releaseNotes: |
    Release v20231207170000.0.0 of package tanzu-java-web-app.dev-ns-02.dieunkrauts.de
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.dieunkrauts.de/tap/workloads/tanzu-java-web-app-dev-ns-02-bundle@sha256:444583e094e635a0a400a01cf3814ebb3cd5b295d013afe69eddfd8d71b64265
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

