apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app.dev-ns-02.dieunkrauts.de.20231126131325.0.0
spec:
  refName: tanzu-java-web-app.dev-ns-02.dieunkrauts.de
  version: 20231126131325.0.0
  releaseNotes: |
    Release v20231126131325.0.0 of package tanzu-java-web-app.dev-ns-02.dieunkrauts.de
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.dieunkrauts.de/tap/workloads/tanzu-java-web-app-dev-ns-02-bundle@sha256:56605bcb307d4257e97b2d43db9eff61274e4c830c261a7759e444b284c56837
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

